backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow
media_folder: "uploads"
public_folder: "uploads"


collections:
  - name: "til"
    label: "TIL post"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{slug}}"
    fields: 
    - {label: "Title", name: "title", widget: "string", required: true}
    - {label: "Body", name: "body", widget: "text"}
    - {label: "Example", name: "example", widget: "markdown"}